nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://(www.)?mediaport.lt']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
