security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginAuthenticator
            logout:
                path: /logout
                target: /
                invalidate_session: true

    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/api, roles: [ROLE_USER, ROLE_ADMIN, ROLE_KLUBO_NARYS] }
         - { path: ^/ticket, roles: [ROLE_USER, ROLE_ADMIN, ROLE_KLUBO_NARYS] }
         - { path: ^/show, roles: [ROLE_USER, ROLE_ADMIN, ROLE_KLUBO_NARYS] }
         - { path: ^/user, roles: [ROLE_USER, ROLE_ADMIN, ROLE_KLUBO_NARYS] }
         - { path: ^/preview, roles: [ROLE_USER, ROLE_ADMIN, ROLE_KLUBO_NARYS] }
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/paysera/new, roles: [ROLE_USER, ROLE_ADMIN, ROLE_KLUBO_NARYS] }
         - { path: ^/paysera/cancel, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/paysera/success, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/paysera/callback, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/subscription, roles: [ROLE_USER, ROLE_ADMIN, ROLE_KLUBO_NARYS] }
